### ISSUE TITLE
[UI] Options form is broken

### ISSUE THREAD

**Issue by SimeonC96** [thien/dinno#102]
![image](https://cloud.githubusercontent.com/assets/3056722/25067377/a3630140-2239-11e7-888e-dd8ea2431613.png)

The "5km" identifier is stuck, we could also lower the max range of the radius from 100 to maybe 50

**Comment by thien** [comment]
fuck ie10

**Comment by JJ97** [comment]
Fraid this is still an issue for IE11

**Comment by thien** [comment]
fixed (y)

**Comment by thien** [comment]
reopened due to the radius not being fixed

**Comment by SimeonC96** [comment]
radius is fine on mine?

**Comment by thien** [comment]
the dragging side; the identifier is stuck but ie11 displays its own value so i can work on hiding that for ie only

**Comment by thien** [comment]
fixed with #125
