### ISSUE TITLE
[NAVBAR] when not logged in

### ISSUE THREAD

**Issue by SimeonC96** [thien/dinno#105]
there is a dropdown called dropdown and misspelling of register
![image](https://cloud.githubusercontent.com/assets/3056722/25067454/ff32f3ac-223b-11e7-88d0-e2d9368d0bbd.png)

EDIT:

no search on navbar for non registered users

**Comment by JJ97** [comment]
think that was @jgbremner  trying something?

**Comment by thien** [comment]
fixed on #115
