### ISSUE TITLE
[ADD] Can't add new tags to meal

### ISSUE THREAD

**Issue by JJ97** [thien/dinno#113]
There doesnt seem to be any code for getting tagId / adding to tag table

**Comment by JJ97** [comment]
Oops i lied. its still not working for some reason tho

**Comment by JJ97** [comment]
oh wait theres a function called addTags that never gets called?

**Comment by SimeonC96** [comment]
yeah add tags doesn't do anything

**Comment by SimeonC96** [comment]
fixed in latest pull request
