### ISSUE TITLE
Fooditems on the map flicker

### ISSUE THREAD

**Issue by thien** [thien/dinno#119]
below is a link to a youtube video which will show you what i mean. 

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/rMxUdZFZvbk/0.jpg)](https://www.youtube.com/watch?v=rMxUdZFZvbk)

**Comment by JJ97** [comment]
Looks like its not getting the bounds of the map properly. Will investigate x

**Comment by JJ97** [comment]
Can't seem to replicate on OSX+chrome/ Windows+IE11. Any chance its an extension you've got installed?

**Comment by thien** [comment]
can't replicate the error here either sadly
