### ISSUE TITLE
Can't add fooditem

### ISSUE THREAD

**Issue by jgbremner** [thien/dinno#128]
Not sure what is causing this - adding a barcode might be required and so its blocking me from submitting as I can't read any barcodes, but no validations so no clue why.

Proof : https://www.youtube.com/watch?v=tKhStdpueQw

**Comment by rs96** [comment]
You have no location, type something into the location box

**Comment by JJ97** [comment]
My bad on the UI front. Since you don't have a current location stored in cookies you have to input one in the textbox. Will change tonight
