### ISSUE TITLE
Chat should show most recent message

### ISSUE THREAD

**Issue by jgbremner** [thien/dinno#129]
This is probably a minor issue but chat history should preferably show the most recent message rather than the older one.
![thien](https://cloud.githubusercontent.com/assets/22935986/25223614/bf5aa13c-25b3-11e7-8dc8-3c15fb5c0dad.png)

**Comment by JJ97** [comment]
swear i fixed this before but w/e

**Comment by JJ97** [comment]
will make it so chat history has a max length too

**Comment by jgbremner** [comment]
Sounds good
