### ISSUE TITLE
Add Tags on Add Fooditem / Edit Fooditem pages

### ISSUE THREAD

**Issue by thien** [thien/dinno#42]
[https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/](https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)

Someone implement this pls

**Comment by thien** [comment]
Also, this will need to obviously work with @SimeonC96 's implementation of the food tagging.

**Comment by SimeonC96** [comment]
Done, just need someone to accept pull request

**Comment by thien** [comment]
pull request accepted on #108
