### ISSUE TITLE
Needs IE Validation

### ISSUE THREAD

**Issue by thien** [thien/dinno#72]

**Comment by rs96** [comment]
yes trying to do it
just wondering if there is any specific style of getting IE stuff working, like so there is a nice neatly seperated IE bit where there needs to be alongside the default?

**Comment by SimeonC96** [comment]
## Things tested on IE

- Adding food
- Deleting food
- Making user accounts
- All search functionality
- Barcode single decodes, can't do live in IE as standard unless I polyfill getUserMedia. Not tested if it queries the db for the name yet

**Comment by thien** [comment]
figured as working, per simeon's satisfaction; see messenger
