### ISSUE TITLE
ie10 navbar is straight up broke

### ISSUE THREAD

**Issue by SimeonC96** [thien/dinno#98]
![image](https://cloud.githubusercontent.com/assets/3056722/25067290/7c52b670-2236-11e7-9f16-6693a7dce496.png)
EDIT: on IE10
![image](https://cloud.githubusercontent.com/assets/3056722/25090458/3349cea0-237b-11e7-9c98-b64c19a9b80b.png)

**Comment by JJ97** [comment]
IE11 navbar is straight up sexy
